PACKAGE_NAME="lockdown_hibernate"
PACKAGE_VERSION="0.1.0"

BUILT_MODULE_NAME[0]="lockdown_hibernate"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make KERNELRELEASE=${kernelver}"

AUTOINSTALL="yes"
